[package]
edition = "2021"
name = "i3wsr"
version = "2.1.1"
description = "Change i3-wm workspace names based on its contents"
authors = ["Daniel Berg <mail@roosta.sh>"]
repository =  "https://github.com/roosta/i3wsr"
documentation =  "https://github.com/roosta/i3wsr"
readme = "README.md"
keywords = ["i3-wm", "window-manager", "workspaces", "linux"]
categories = ["command-line-utilities"]
license = "MIT"
exclude = ["/script", "/assets/*", "Vagrantfile"]

[badges]
travis-ci = { repository = "roosta/i3wsr" }

[dependencies]
xcb = "1.2.1"
clap = { version = "4.3.11", features = ["derive"] }
toml = "0.7.6"
serde = { version = "1.0.171", features = ["derive"] }
itertools = "0.11.0"
regex = "1.9.1"
encoding = "0.2"
dirs = "5.0.1"
i3ipc = "0.10.1"

